### ISSUE TITLE
Including address of the buyer/seller

### ISSUE THREAD

**Issue by xori** [cryptto-io/market-data-feed#1]
Is there a reason why you don't include the address of the buyer/seller for aggregating small transactions together to a single source?

**Comment by deniscryptto** [comment]
Xori, thank you for pointing this out.  We did not include this info day 1 to optimize bandwidth usage, and because we did not expect it to be popular with users.
Some exchanges publish order ID for makers only, and some for both sides.  If we were to include this in a later release but limit it to a single side, which would you prefer?
